#!/usr/bin/env python
import os

env = SConscript("../../godot-cpp/SConstruct")

env.Append(CPPPATH=["src/", "../shared/include/"])
sources = [Glob("src/*.cpp")]

addon_bin = "../../game/addons/marionette/bin"
if not os.path.isdir(addon_bin):
    os.makedirs(addon_bin, exist_ok=True)

if env["platform"] == "macos":
    library = env.SharedLibrary(
        "{}/libmarionette.{}.{}.framework/libmarionette.{}.{}".format(
            addon_bin, env["platform"], env["target"], env["platform"], env["target"]
        ),
        source=sources,
    )
else:
    library = env.SharedLibrary(
        "{}/libmarionette{}{}".format(addon_bin, env["suffix"], env["SHLIBSUFFIX"]),
        source=sources,
    )

Default(library)
