@tool
class_name CollisionExclusionProfile
extends Resource

# P3.4 — pairs of Skeleton3D bone indices whose physical bodies should NOT
# generate collision contacts, plus a list of bone names to omit entirely
# from the physical skeleton.
#
# Indices index into the *Skeleton3D* the ragdoll is built against, so a
# profile is rig-specific. Generated by `parent_child_defaults(skel)` and
# editable in inspector. `disabled_bones` uses canonical SkeletonProfile
# bone names so it's portable across rigs that share a profile.

@export var excluded_pairs: Array[Vector2i] = []
@export var disabled_bones: PackedStringArray = []


# Generates parent-child default exclusions: every parent->child pair in the
# skeleton hierarchy. Set `include_siblings=true` to also exclude pairs of
# children sharing a parent (useful when knee colliders touch in T-pose).
static func parent_child_defaults(skel: Skeleton3D, include_siblings: bool = false) -> CollisionExclusionProfile:
	var p := CollisionExclusionProfile.new()
	if skel == null:
		return p
	var n: int = skel.get_bone_count()
	var children_of: Dictionary[int, Array] = {}
	for i in range(n):
		var parent: int = skel.get_bone_parent(i)
		if parent < 0:
			continue
		p.excluded_pairs.append(Vector2i(parent, i))
		if not children_of.has(parent):
			children_of[parent] = []
		children_of[parent].append(i)
	if include_siblings:
		for siblings: Array in children_of.values():
			for a_idx in range(siblings.size()):
				for b_idx in range(a_idx + 1, siblings.size()):
					p.excluded_pairs.append(Vector2i(siblings[a_idx], siblings[b_idx]))
	return p


# True if the named bone is on the disabled list (compared by canonical name).
func is_disabled(bone_name: StringName) -> bool:
	return disabled_bones.has(String(bone_name))
